### PR TITLE
Support native module in windows

### PR DESCRIPTION
**Pull request by ScSofts**
Support native module in windows using LoadLibrary. LoadLibraryEx doesn't work,and I'm confused about it.

### CODE REVIEW

**Comment by ScSofts** [comment]
Hi.I wan't to use it in my application development,and I found I need this feature。 WinAPI ` LoadLibray ` is OK,but `LoadLibraryEx ` doesn't work as expected and it returned a NULL value, and do you know why?

**Comment by c-smile** [comment]
You haven't changed this line:
```if (has_suffix(module_name, ".so")) {```

@ScSofts, is this intentional? I believe this should handle ```.dll``` (Windows) and ```.dylib``` (MacOS) cases.

**Comment by ScSofts** [comment]
> You haven't changed this line:
> `if (has_suffix(module_name, ".so")) {`
> 
> @ScSofts, is this intentional? I believe this should handle `.dll` (Windows) and `.dylib` (MacOS) cases.

I have found that it can be specified by using macro such as ` WIN32` 、` __linux__ ` and ` __APPLE__ ` ,and the macos dylib can also be loaded by the api ` dlopen `.

**Comment by ScSofts** [comment]
I have fixed it.

**Pull request merged**
